[package]
name = "rusoto_cloudformation_ext"
version = "0.1.0"
authors = ["Chris Connelly <chris@connec.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stream = "0.3.0"
chrono = "0.4.19"
futures-util = "0.3.14"
memmem = "0.1.1"
rusoto_cloudformation = "0.46.0"
rusoto_core = "0.46.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_plain = "0.3.0"
thiserror = "1.0.24"
tokio = { version = "1.4.0", features = ["time"] }
tokio-stream = "0.1.5"

[dev-dependencies]
fastrand = "1.4.0"
rusoto_credential = "0.46.0"
