name: PR

on:
  pull_request:
    branches:
      - master

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          key: ${{ github.sha }}
          path: |
            ~/.cargo
            target
      - name: Check
        run: cargo check

  clippy:
    runs-on: ubuntu-20.04
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          key: ${{ github.sha }}
          path: |
            ~/.cargo
            target
      - name: Clippy
        run: cargo clippy

  doc-check:
    runs-on: ubuntu-20.04
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          key: ${{ github.sha }}
          path: |
            ~/.cargo
            target
      - name: Doc check
        run: cargo doc --no-deps

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: cargo test
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
